apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-staging  # Specifies the Cluster Issuer to use
spec:
  tls:
  - hosts:
    - joesak.com
    secretName: tls-web  # Secret name is used to dynamically generate the secret
  rules:
  - host: joesak.com
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80