apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod # Specifies the Cluster Issuer to use
spec:
  tls:
  - hosts:
    - joesak.com
    - www.joesak.com
    secretName: web-tls
  rules:
  - host: joesak.com
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80