name: Docker Image CI

env:
  GIT_REF: ${{ github.ref }}
  GIT_SHA: ${{ github.sha }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to docker
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - uses: actions/checkout@v2
    - name: Build the docker image
      run: docker build . --file Dockerfile --tag joemsak/joesak.com:$GIT_SHA

    - uses: actions/checkout@v2
    - name: Push the docker image
      run: docker push joemsak/joesak.com:$GIT_SHA

    - uses: actions/checkout@v2
    - name: Update k8s deployment
      run: sed -i "s/latest/${CI_COMMIT_SHORT_SHA}/g" .kubernetes/deployment.yaml

    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy k8s infra
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        args: apply -k .kubernetes
